/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package orderProcessing;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author mdr5325
 */

public class PointOfSaleUI extends javax.swing.JFrame {

    private static PointOfSaleUI UI = new PointOfSaleUI( );
    
    public int orderType = -1;
    
    public static final int BUY = 1;
    public static final int RETURN = 2;
    public static final int INVENTORY_ADJUSTMENT = 3;
    public static final int EXCHANGE = 4;
    /**
     * Creates new form PointOfSaleUI
     */
    public PointOfSaleUI() {
        initComponents();
    }
    
    public synchronized static PointOfSaleUI getInstance( ) {
      return UI;
    }
    
    protected void sendAlertMessage(String message)
    {
        JOptionPane.showMessageDialog(null, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Inventory Adjustment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exchange");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("item:");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("quantity:");

        jLabel3.setText("for another item:");
        jLabel3.setName(""); // NOI18N

        jButton5.setText("Submit Transaction");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel Transaction");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        jLabel2.setVisible(false);
        jTextField2.setVisible(false);
        jLabel3.setVisible(false);
        jTextField3.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // BUY BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        prepareForASingleItemTransaction();
        orderType = 1;
    }//GEN-LAST:event_jButton1ActionPerformed

    // RETURN BUTTON
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        prepareForASingleItemTransaction();
        orderType = 2;
    }//GEN-LAST:event_jButton2ActionPerformed

    // INVENTORY ADJUSTMENT BUTTON
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        prepareForASingleItemTransaction();
        orderType = 3;
    }//GEN-LAST:event_jButton3ActionPerformed

    // EXCHANGE BUTTON
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        prepareForAMultipleItemTransaction();
        orderType = 4;
    }//GEN-LAST:event_jButton4ActionPerformed

    // CANCEL TRANSACTION BUTTON
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        enableAllTransactionTypeButtons();
        setAllItemRelatedControlsInvisible();
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        String firstItemName = jTextField1.getText();
        int firstItemQuantity = jTextField2.isVisible() && isInteger(jTextField2.getText()) ? 
                Integer.parseInt(jTextField2.getText())
                : -1;
        
        if (firstItemQuantity == -1 && jTextField2.isVisible()){
            sendAlertMessage("you must enter a number");
            return;
        }
        
        startClient(orderType, firstItemName, firstItemQuantity);

        
        //try{
        /*switch(orderType){
            case BUY:
                OrderProcessing.submitBuyTransaction(firstItemName, firstItemQuantity);
                break;
            case RETURN:
                OrderProcessing.submitReturnTransaction(firstItemName, firstItemQuantity);
                break;
            case INVENTORY_ADJUSTMENT:
                OrderProcessing.submitInventoryAdjustmentTransaction(firstItemName, firstItemQuantity);
                break;
            case EXCHANGE:
                String secondItemName = jTextField3.getText();
                OrderProcessing.submitExchangeTransaction(firstItemName, secondItemName);
                break;
        }*/
        
        setAllItemRelatedControlsInvisible();
        enableAllTransactionTypeButtons();
        
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    public boolean isInteger(String s) {
        try { 
            Integer.parseInt(s); 
        } catch(NumberFormatException e) { 
            return false; 
        } catch(NullPointerException e) {
            return false;
        }

        return true;
    }
    private void prepareForASingleItemTransaction(){
        setFirstItemAndQuantityVisible();
        disableAllTransactionTypeButtons();
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
    }
    
    private void prepareForAMultipleItemTransaction(){
        setFirstItemVisible();
        setSecondItemVisible();
        disableAllTransactionTypeButtons();
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
    }
    
    private void setFirstItemAndQuantityVisible(){
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
        
        jLabel2.setVisible(true);
        jTextField2.setVisible(true);
    }
    
    private void setFirstItemVisible(){
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
    }
    
    private void setSecondItemVisible(){
        jLabel3.setVisible(true);
        jTextField3.setVisible(true);
    }
    
    private void setAllItemRelatedControlsInvisible(){
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        
        jLabel2.setVisible(false);
        jTextField2.setVisible(false);
        
        jLabel3.setVisible(false);
        jTextField3.setVisible(false);
        
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
    }
    
    private void disableAllTransactionTypeButtons(){
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
    }
    
    private void enableAllTransactionTypeButtons(){
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);
        jButton4.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PointOfSaleUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PointOfSaleUI().setVisible(true);
            }
        });
        
       
    }
    
    public static void startClient(int orderType, String firstItemName, int firstItemQuantity){
        String serverName = "localhost";
        int port = 5001;
        Socket serverConnection = makeConnection(serverName, port);
        //Thread clientMessageHandler = new ClientMessageHandler(serverConnection);
        //clientMessageHandler.start();

        try
        {            
            sendMessage(serverConnection, orderType, firstItemName, firstItemQuantity);
        }
        catch(Exception e)
        {
            System.out.println("Exception in TalkClient main()");
        }	
    }
    
    public static Socket makeConnection(String serverName, int port)
    {
        Socket serverConnection = null;
        try
        {

                System.out.println("Connecting to " + serverName + " on port " + port);
                serverConnection = new Socket(serverName, port);
                System.out.println("Just connected to " + serverConnection.getRemoteSocketAddress());
                OutputStream outToServer = serverConnection.getOutputStream();
                DataOutputStream dataOutToServer = new DataOutputStream(outToServer);
                dataOutToServer.writeUTF("Hello from " + serverConnection.getLocalSocketAddress());
                InputStream inFromServer = serverConnection.getInputStream();
                DataInputStream dataIn = new DataInputStream(inFromServer);
                System.out.println("Server says: " + dataIn.readUTF());
        }
        catch(IOException e)
        {
                System.out.println("IOException in TalkClient makeConnection()");
        }
        return serverConnection;
    }
    
    public static void sendMessage(Socket serverConnection, int orderType, String firstItemName, int firstItemQuantity)
    {
        try
        {
                OutputStream outToServer = serverConnection.getOutputStream();
                DataOutputStream dataOutToServer = new DataOutputStream(outToServer);
                dataOutToServer.writeInt(orderType);
                dataOutToServer.writeUTF(firstItemName);
                dataOutToServer.writeInt(firstItemQuantity);

        }
        catch(IOException e)
        {
                System.out.println("IOException in TalkClient sendMessage()");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
